//     [Slide]
//   ## Graph Terminology: Node, Edges, Direction and Weight

//   ![placekitten](http://placekitten.com/800/600)
//   [/Slide]

//    [Slide]
//   ## Graph Terminology: Cycles

//   ![placekitten](http://placekitten.com/800/600)
//   [/Slide]


 
 
 // [Slide]
  // ## But what are these **objects** and what are these **relations**?
  // [/Slide]

  // [Slide]
  // ## Exhibit A: HVV

  // ![placekitten](http://placekitten.com/800/600)
  // [/Slide]

  // [Slide]
  // ## Exhibit B: The DASHboard

  // ![placekitten](http://placekitten.com/800/600)
  // [/Slide]

  // [Slide]
  // ## Exhibit C: KarDASHians™

  // ![placekitten](http://placekitten.com/800/600)
  // [/Slide]